import { test, expect } from '@playwright/test';

test('signup', async ({ page }) => {
  await page.goto('http://localhost:8000/');
  await page.getByRole('button', { name: 'Get Started' }).first().click();
  await page.getByPlaceholder('username').click();
  await page.getByPlaceholder('username').fill('user');
  await page.getByPlaceholder('password').click();
  await page.getByPlaceholder('password').fill('123');
  await page.getByPlaceholder('password').press('Enter');
  await page.getByPlaceholder('password').press('Enter');
  await page.getByRole('link', { name: 'Join Now!' }).click();
  await page.getByPlaceholder('Full Name').click();
  await page.getByPlaceholder('Full Name').fill('ce');
  await page.getByRole('button', { name: 'Log In' }).click();
  await page.getByPlaceholder('username').click();
  await page.getByPlaceholder('username').fill('celina');
  await page.getByPlaceholder('password').click();
  await page.getByPlaceholder('password').fill('123');
  await page.getByPlaceholder('password').press('Enter');
  await page.getByPlaceholder('password').press('Enter');
  await page.getByRole('link', { name: 'Join Now!' }).click();
  await page.getByPlaceholder('Full Name').click();
  await page.getByPlaceholder('Full Name').fill('celina');
  await page.getByPlaceholder('username').click();
  await page.getByPlaceholder('username').fill('celina');
  await page.getByPlaceholder('email').click();
  await page.getByPlaceholder('email').fill('celina');
  await page.getByPlaceholder('password').click();
  await page.getByPlaceholder('password').fill('123');
  await page.getByRole('button', { name: 'sign up' }).click();
  await page.locator('input[name="file"]').click();
  await page.locator('input[name="file"]').click();
  await page.locator('input[name="file"]').setInputFiles('Screenshot 2024-11-17 at 7.49.57 PM.png');
  await page.getByRole('button', { name: 'sign up' }).click();
  await page.getByRole('button', { name: 'sign up' }).click();
  await page.getByPlaceholder('password').fill('123');
  await page.getByRole('button', { name: 'sign up' }).click();
  await page.goto('http://localhost:8000/accounts/signup/');
  await expect(page.getByText('Have an account? Login')).toBeVisible();
});